spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: servicecloud-config-wzb-dev
---
spring:
  profiles: test #测试环境
  application:
    name: servicecloud-config-wzb-test
# 请保存为UTF-8格式    
# 分支feature